### ISSUE TITLE
A Suggestion

### ISSUE THREAD

**Issue by Thegamerprogrammer** [ValMobile/RealisticSurvival#10]
Val, I Am Wondering If U Could Add Weight and Gravity To The Plugin I Have Tried Ur Plugin Its Awesome. But Could U Please Add Weight ANd Gravity?

**Comment by ValMobile** [comment]
Thank you for your suggestion! Unfortunately, I won't be able to implement it currently due to time constraints and the vague description of it. In the meantime, please elaborate more on how this weight and gravity system would work.

**Comment by ValMobile** [comment]
Closed due to a lack of response in a reasonable timeframe
