### ISSUE TITLE
bug crafting

### ISSUE THREAD

**Issue by NikolasGregor** [ValMobile/RealisticSurvival#15]
how do i craft the custom items that the plugin adds? i can see them in the recipes but i cant craft them in the crafting table, what do i do?

**Comment by ValMobile** [comment]
Closed due to a lack of information and reproducibility on the issue. The problem description sounds similar to uncraftable Spartan weapons. See [the common issues guide](https://github.com/ValMobile/RealisticSurvival/wiki/Common-Issues) for solutions.
