### ISSUE TITLE
I want take and add thirst added to the command line

### ISSUE THREAD

**Issue by olivergame** [ValMobile/RealisticSurvival#18]
### ❗ Checklist

- [X] I have checked that my requested feature does not exist on the most up-to-date "dev-build" (not "Spigot") version of Realistic Survival.
- [X] I know that feature requests related to other plugins need to be reported on their feature request trackers and not here.
- [X] I searched for similar feature requests and could not find an existing form on this.
- [X] I know that feature requests should align to Realistic Survival's goal of recreating the RLCraft modpack experience.
- [X] I understand that my requested feature may not be added due to time constraints or other limitations.

### 📍 What problem do you want to solve?

Dear community
I want @p be added to the command line
exemple:
/rsv thirst playername [thirst -5]

why? Because i wanna people to be able to push a command  block or somthing similar to have there thirst restore or change in negative way.

There are a few other things i can do as well if this command is added.

### 💡 What would you change, add, or modify to solve the problem?

add
/rsv thirst playername [thirst +/- level]
or
/rsv thirst playername add thirst +x 
/rsv thirst playername take thirst +x

### 🌐 How do you see your suggestion benefiting the majority of servers?

with help of command block or other systems of using this commands.
Server owner wil be able to create a save zone for where people can stay .
places to be use:
lobby
pool of water
bar
or other save zones server owners can think off.

this also can be use to create a danger zone. 
places to be use:
world border
places there say it hot 

this is how a command block can be look like if this command option is added:
execute as @p[x=0,y=65,x=0,distance=..2] rsv thirst playername [thirst +/- level] ( this command is not tested)

how i will use it :
i will use it for my realistic roleplay server
this will give me a lot op options like makeing custom items ,save and danger zones, even a shower healt option or drinking from the pool will be work for my if this 1 command option wil be added. 

why i think this will benifits the Dev's
This way the Dev's do not have to make a special config line to make it work 
for regios and other situations  like more items in my mind

i hope this request does not add a lot of work to do

### 🎮 Module

Tough as Nails

### 💰 Donations and Partnerships

- [ ] I fall into one of the categories listed above.

**Comment by olivergame** [comment]
as i look in the config you have [ThirstPoints:]
if that can be added as a command and be optional to have ThirstPoints: -3.0 and ThirstPoints: 3.0

so a command like can look like 
/rsv give playername ThirstPoints 3
/rsv give playername ThirstPoints -3

**Comment by ValMobile** [comment]
Feature added as of 1.2.5-RELEASE
