### ISSUE TITLE
hud options

### ISSUE THREAD

**Issue by olivergame** [ValMobile/RealisticSurvival#20]
### ❗ Checklist

- [X] I have checked that my requested feature does not exist on the most up-to-date "dev-build" (not "Spigot") version of Realistic Survival.
- [X] I know that feature requests related to other plugins need to be reported on their feature request trackers and not here.
- [X] I searched for similar feature requests and could not find an existing form on this.
- [X] I know that feature requests should align to Realistic Survival's goal of recreating the RLCraft modpack experience.
- [X] I understand that my requested feature may not be added due to time constraints or other limitations.

### 📍 What problem do you want to solve?

the option to turn on or of the hud 
and have papi placeholder for it

### 💡 What would you change, add, or modify to solve the problem?

in the config file  the option
# hud 
Show thirst : true/false
Show temperature : true/false
Show hunger : true/false
Show saturation : true/false

papi placeholder
%thirst% for thirst
%temperature% for temperature

### 🌐 How do you see your suggestion benefiting the majority of servers?

it will give me the option for a custom HUD change and it will not bother other HUD's of other plugins or mods

as for other people/servers i think same reason 

### ⚙ How might you implement your solution in code?

no idea i have not add the hud in the first place

### 🎮 Module

Tough as Nails

### 🧭 Plugin Dependencies

papi placeholder

### 💰 Donations and Partnerships

- [ ] I fall into one of the categories listed above.

### ✨ Additional Comments

As for now i do not need it because i was able to change the hud of a other plugin that was in conflict with this one.

**Comment by ValMobile** [comment]
Placeholders are added as of version 1.2.5-RELEASE
