### ISSUE TITLE
Double jump

### ISSUE THREAD

**Issue by WhoAmI2704** [ValMobile/RealisticSurvival#22]
### ❗ Checklist

- [X] I am using the official version of Realistic Survival and did not modify the jar.
- [X] I am using an up-to-date "dev-build" (not "Spigot") version of Realistic Survival.
- [X] I know that issues related to other plugins need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when I jump or get hit i suffer from double jump

### 📑 Reproduction Steps

Jump or get attacked

### 💡 Expected Behavior

Jump once not twice

### 📷 Screenshots / Videos

https://www.mediafire.com/file/18rw7x7actbv60t/f%2Ack_double_jump.mp4/file

### 📜 Server Log

No errors or any log about the double jump

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.19.x

### ⭐ Realistic Survival version

![image](https://user-images.githubusercontent.com/73607167/213971248-7244b6e3-2003-4766-8d77-9b4ab757fe14.png)

### 🧭 Other plugins

Non related

**Comment by ValMobile** [comment]
Hi, this is caused by latency in your server. There is no way to prevent it since plugins are server-side modifications and are affected by lag.
