### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by landoncrabtree** [ValMobile/RealisticSurvival#23]
### ❗ Checklist

- [X] I am using the official version of Realistic Survival and did not modify the jar.
- [X] I am using an up-to-date "dev-build" (not "Spigot") version of Realistic Survival.
- [X] I know that issues related to other plugins need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

```
[15:23:55 ERROR]: Could not pass event PlayerJoinEvent to RealisticSurvival v1.2.4-RELEASE
java.lang.NullPointerException: Cannot invoke "me.val_mobile.data.RSVConfig.getConfig()" because the return value of "me.val_mobile.data.RSVModule.getUserConfig()" is null
```

### 📑 Reproduction Steps

1. Login to the server
2. Error

### 💡 Expected Behavior

There should be no NPE related to logging in.

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Realistic Survival version

1.2.4-RELEASE

### 🧭 Other plugins

No other plugins loaded.

**Comment by ValMobile** [comment]
This is a bug. PieMC discussed the solution on Discord, but I will restate it in case other people search for past issues (and their solutions) on the GitHub issue tracker. You can solve this by enabling the Ice And Fire module and disabling it on all your worlds.
