### ISSUE TITLE
Gui modification bug

### ISSUE THREAD

**Issue by NoMercyPeace** [ValMobile/RealisticSurvival#27]
### ❗ Checklist

- [X] I am using the official version of Realistic Survival and did not modify the jar.
- [ ] I am using an up-to-date "dev-build" (not "Spigot") version of Realistic Survival.
- [X] I know that issues related to other plugins need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

the RSVitem: gui_glass in the baubles folder doesnt change in the game gui but if i give it to me by command it shows that its fuctioning i think the problem is in the .jar file

### 📑 Reproduction Steps

1. go to C:\Users\Desktop\server\plugins\RealisticSurvival\resources\baubles and open the item.yml file
2. search gui_glass in the file and add a row (CustomModelData: number)
![Immagine 2023-03-12 135404](https://user-images.githubusercontent.com/127667114/224545987-9c92f99b-83b3-4664-b9ff-160660d4d68a.png)

3 add the custom item with the custommodeldata in the resource pack
 1\ baubles model folder
![Immagine 2023-03-12 135848](https://user-images.githubusercontent.com/127667114/224546334-2b4d1432-510b-4d22-a0a3-473423f82592.png)

 2\ minecraft model folder .json (custommodeldata folder)
![Immagine 2023-03-12 140012](https://user-images.githubusercontent.com/127667114/224546385-f97e7885-d5c8-4474-8266-fe1f3fea55b0.png)

4 restart your server
5 open the baubles bag
6 write the command /rsv give %player_name% gui_glass

### 💡 Expected Behavior

i wanted to do a clear design for the baubles bag like in the png
![Immagine 2023-03-12 134223](https://user-images.githubusercontent.com/127667114/224545388-74ca310b-0877-4bb0-92e2-288a5ceae70f.png)
but it wasnt changing

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Realistic Survival version

1.2.4

### 🧭 Other plugins

i have weaponry plus but i've merged it whit the RSV resource pack, and it never done any problem

**Comment by NoMercyPeace** [comment]
Solved: 
The changes will only be applied to new bauble guis that are re-created
Pre-existing ones won't be affected. You'll have to delete your baubles/playerdata.yml file and let it regenerate

**Comment by ValMobile** [comment]
The bauble gui should automatically update as of version 1.2.5-RELEASE. It did not previously. Let me know if this is the case.
