### ISSUE TITLE
Game Breaking Bug in Bauble Bag Charms

### ISSUE THREAD

**Issue by crush4win** [ValMobile/RealisticSurvival#30]
### ❗ Checklist

- [X] I am using the official version of Realistic Survival and did not modify the jar.
- [X] I am using an up-to-date "dev-build" (not "Spigot") version of Realistic Survival.
- [X] I know that issues related to other plugins need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

After placing any item in the bauble bag, when you move the mouse over that item and press ctrl + q, the item is duplicated.

### 📑 Reproduction Steps

1. Put a charm in the bauble bag
2. Afterwards, when the mouse is over the charm but don't hold the item, just move the mouse over it Ctrl + q to duplicate the item. 

### 💡 Expected Behavior

The item should not have been dupe. He should have just thrown it on the ground

### 📷 Screenshots / Videos

![Screenshot (98)](https://github.com/ValMobile/RealisticSurvival/assets/120653521/24f473e1-4116-46c1-adb8-ef481f952cef)
![Screenshot (99)](https://github.com/ValMobile/RealisticSurvival/assets/120653521/8953c204-5976-4131-86e6-8c2420b447ad)

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Realistic Survival version

1.2.5 DEV-1

**Comment by ValMobile** [comment]
Should be fixed as of 1.2.5-RELEASE. Let me know if the issue persists.
