### ISSUE TITLE
Bauble Bag Error Breaking The Plugin

### ISSUE THREAD

**Issue by crush4win** [ValMobile/RealisticSurvival#31]
### ❗ Checklist

- [X] I am using the official version of Realistic Survival and did not modify the jar.
- [X] I am using an up-to-date "dev-build" (not "Spigot") version of Realistic Survival.
- [X] I know that issues related to other plugins need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I open Bauble Bag, there is no problem when I press ctrl+q on the slots where you can put items with a normal mouse. But if you take an item in your hand, for example ankh charm, and while holding this item with the mouse, if you come to the bauble bag slot and press ctrl+q, this time the empty item view in the slot goes away and the slot becomes unusable

### 📑 Reproduction Steps

Open Bauble Bag
Go to empty item slots while holding items with your mouse
Press Ctrl + q and you will see that the empty slot view disappears
That slot can't be used again

### 💡 Expected Behavior

The free slot must not disappear and the slot must be reusable

### 📷 Screenshots / Videos

![Screenshot (110)](https://github.com/ValMobile/RealisticSurvival/assets/120653521/10ed8d27-39cb-4b81-a3f2-4a1f16c02eff)
![Screenshot (111)](https://github.com/ValMobile/RealisticSurvival/assets/120653521/488604c3-cb42-4fd3-b266-12dde397229e)
![Screenshot (112)](https://github.com/ValMobile/RealisticSurvival/assets/120653521/17544763-6dce-4831-9ac4-98f3fd0d2a65)

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Realistic Survival version

![Screenshot (113)](https://github.com/ValMobile/RealisticSurvival/assets/120653521/aaf05fa7-8e00-499e-a0f5-de6953a2872e)

**Comment by ValMobile** [comment]
Fixed in 1.2.6-RELEASE.
