### ISSUE TITLE
Thirst Error

### ISSUE THREAD

**Issue by xIcee** [ValMobile/RealisticSurvival#9]
Occasionally, drinking water does not satiate thirst. The thirst bar does not increase, and the players eventually die as such. After respawn, thirst works again.

**Comment by xIcee** [comment]
After further exploration, I realize the thirst fails at about half or lower thirst level, and relogging fixes it.

**Comment by ValMobile** [comment]
You can replenish thirst by right or left-clicking source blocks of water.
